###############################################################################
# General Configuration
###############################################################################
version: 1.0.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2017

configuration: 
 - Release
 - Debug

environment:
  matrix:
  - solution_name: cs-smallpt/cs-smallpt.sln
  #- solution_name: threads-cs-smallpt/cs-smallpt.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%
